### ISSUE TITLE
windframework是什么协议的框架？

### ISSUE THREAD

**Issue by ghost** [phpwind/windframework#4]
windframework是什么协议的框架？
如果没有一款开源协议，谁敢用？

谁会拿来开发自己的应用程序？

谁敢冒这样的风险？

**Comment by phpwind** [comment]
非常抱歉，关于协议，我们正在请公司的法务做最后的相关确认～

**Comment by ghost** [comment]
如果不是开源许可证那么我想我是不会考虑使用 windframework。就算你技术再好，再先进，设计再好。

开源世界里面已经有很多优秀的框架。

虽然我很高兴看到PW推出ＰＨＰ框架。但是没有一个名正言顺的许可证　，大家还是很难品尝这么好的大餐的。

ｐｗ想走收费框架的道路？

**Comment by phpwind** [comment]
虽然协议还没有最后确认～ 但是肯定开源～
大家用不用放在一边，我们在和大家分享我们的理念，设计思路～ 我希望收到共鸣

**Comment by ghost** [comment]
理解你作为技术人员的愿景。但是作为coder的我， 如果知道这款框架，没有标准的开源协议，那么我是不会去吸收你们好的理念，设计思路 。 因为这种感觉就像是窃取一样。  如果是开源，那么我不仅会努力吸收你们好的设计思路，代码，我还会积极的参与贡献，提交反馈，贡献代码。

因为它是真正开放的。

**Comment by ttgive** [comment]
框架理念你吸收就好了

**Comment by phpwind** [comment]
http://www.phpwind.com/license.php

**Comment by ghost** [comment]
恭喜恭喜， 第一时间恭贺 PHPWind 推出　　BSD许可协议的开源框架。

**Comment by zlxy** [comment]
http://www.phpwind.com/license.php 打不开？
